/**
 * Map des anciennes URLs V1 vers les nouveaux identifiants V2.
 *
 * Clé : l'ancien chemin après /parks/ (ex: "universalstudios/universalstudios-hollywood")
 * Valeur : le nouveau slug V2 (ex: "universal-studios-hollywood")
 *
 * Exemple :
 *   "universalstudios/universalstudios-hollywood": "universal-studios-hollywood",
 */
export const legacyParkRedirects: Record<string, string> = {
  "disneyland/animal-kingdom": "animal-kingdom",
  "disneyland/california-adventure": "california-adventure",
  "disneyland/disney-adventure-world": "disney-adventure-world",
  "disneyland/disneylandparis-park": "disneyland-paris",
  "disneyland/epcot": "epcot",
  "disneyland/hollywood-studios": "hollywood-studios",
  "disneyland/hongkong-disneyland": "hong-kong-disneyland",
  "disneyland/magic-kingdom-california": "disneyland-california",
  "disneyland/magic-kingdom-florida": "magic-kingdom-florida",
  "disneyland/shanghai-disneyland": "shanghai-disneyland",
  "disneyland/tokyo-disneysea": "tokyo-disneysea",
  "disneyland/tokyo-disneyland": "tokyo-disneyland",
  "universalstudios/universal-epic-universe": "universal-epic-universe",
  "universalstudios/universalstudios-beijing": "universal-beijing",
  "universalstudios/universalstudios-florida": "universal-studios-florida",
  "universalstudios/universalstudios-hollywood": "universal-studios-hollywood",
  "universalstudios/universalstudios-japan": "universal-studios-japan",
  "universalstudios/universal-islands-of-adventure":
    "universal-islands-of-adventure",
  "universalstudios/universal-volcano-bay": "universal-volcano-bay",
  "seaworld/busch-gardens-tampa": "busch-gardens-tampa",
  "seaworld/busch-gardens-williamsburg": "busch-gardens-williamsburg",
  "seaworld/seaworld-orlando": "seaworld-orlando",
  "seaworld/seaworld-san-antonio": "seaworld-san-antonio",
  "seaworld/seaworld-san-diego": "seaworld-san-diego",
  "cedarfair/californias-great-america": "californias-great-america",
  "cedarfair/canadas-wonderland": "canadas-wonderland",
  "cedarfair/carowinds": "carowinds",
  "cedarfair/cedar-point": "cedar-point",
  "cedarfair/dorney-park": "dorney-park",
  "cedarfair/kings-dominion": "kings-dominion",
  "cedarfair/kings-island": "kings-island",
  "cedarfair/knotts-berry-farm": "knotts-berry-farm",
  "cedarfair/michigans-adventure": "michigans-adventure",
  "cedarfair/valleyfair": "valleyfair",
  "cedarfair/worlds-of-fun": "worlds-of-fun",
  "compagnie-alpes/bellewaerde": "bellewaerde",
  "compagnie-alpes/familypark": "familypark",
  "compagnie-alpes/futuroscope": "futuroscope",
  "compagnie-alpes/parc-asterix": "parc-asterix",
  "compagnie-alpes/walibi-belgium": "walibi-belgium",
  "compagnie-alpes/walibi-holland": "walibi-holland",
  "compagnie-alpes/walibi-rhone-alpes": "walibi-rhone-alpes",
  "portaventura-world/ferrari-land": "ferrari-land",
  "portaventura-world/portaventura": "portaventura-park",
  "studio-100/plopsaland": "plopsaland-belgium",
  "studio-100/plopsaland-deutschland": "plopsaland-deutschland",
  "merlin/alton-towers": "alton-towers",
  "merlin/chessington-world-of-adventures": "chessington-world-of-adventures",
  "merlin/gardaland": "gardaland",
  "merlin/heide-park": "heide-park",
  "merlin/legoland-billund": "legoland-billund",
  "merlin/legoland-california": "legoland-california",
  "merlin/legoland-deutschland": "legoland-deutschland",
  "merlin/legoland-florida": "legoland-florida",
  "merlin/legoland-japan": "legoland-japan",
  "merlin/legoland-korea": "legoland-korea",
  "merlin/legoland-new-york": "legoland-new-york",
  "merlin/legoland-shanghai": "legoland-shanghai",
  "merlin/legoland-windsor": "legoland-windsor",
  "merlin/peppa-pig-theme-park": "peppa-pig-theme-park-florida",
  "merlin/thorpe-park": "thorpe-park",
  "grupa-ptak/mandoria": "mandoria",
  "grupa-ptak/parc-du-petit-prince": "parc-du-petit-prince",
  "herschend/adventureland": "adventureland-resort",
  "herschend/dollywood": "dollywood",
  "herschend/kennywood": "kennywood",
  "herschend/lake-compounce": "lake-compounce",
  "herschend/silver-dollar-city": "silver-dollar-city",
  "village-roadshow/sea-world": "sea-world-australia",
  "village-roadshow/warner-bros-movie-world":
    "warner-bros-movie-world-australia",
  "village-roadshow/wet-n-wild-gold-coast": "wet-n-wild-gold-coast",
  "beto-carrero-world": "beto-carrero-world",
  "blackpool-pleasure-beach": "blackpool-pleasure-beach",
  "cinecitta-world": "cinecitta-world",
  "djurs-sommerland": "djurs-sommerland",
  efteling: "efteling",
  energylandia: "energylandia",
  "europa-park": "europa-park",
  fantasilandia: "fantasilandia",
  "farup-sommerland": "farup-sommerland",
  "flamingo-land": "flamingo-land",
  "fujiq-highland": "fuji-q-highland",
  "grona-lund": "grona-lund",
  "hansa-park": "hansa-park",
  hersheypark: "hershey-park",
  knoebels: "knoebels",
  "le-pal": "le-pal",
  liseberg: "liseberg",
  nigloland: "nigloland",
  "ocean-park": "ocean-park",
  "parc-spirou": "parc-spirou",
  "paultons-park": "paultons-park",
  phantasialand: "phantasialand",
  rulantica: "rulantica",
  "tokyo-dome-city": "tokyo-dome-city",
  toverland: "toverland",
  "parques-reunidos/bobbejaanland": "bobbejaanland",
  "parques-reunidos/movie-park-germany": "movie-park-germany",
  "parques-reunidos/parque-atracciones-madrid": "parque-de-atracciones-madrid",
  "parques-reunidos/parque-warner-madrid": "parque-warner-madrid",
  "six-flags/frontier-city": "frontier-city",
  "six-flags/laronde-montreal": "la-ronde",
  "six-flags/six-flags-darien-lake": "six-flags-darien-lake",
  "six-flags/six-flags-discovery-kingdom": "six-flags-discovery-kingdom",
  "six-flags/six-flags-fiesta-texas": "six-flags-fiesta-texas",
  "six-flags/six-flags-great-adventure": "six-flags-great-adventure",
  "six-flags/six-flags-great-america": "six-flags-great-america",
  "six-flags/six-flags-great-escape": "six-flags-great-escape",
  "six-flags/six-flags-magic-mountain": "six-flags-magic-mountain",
  "six-flags/six-flags-mexico": "six-flags-mexico",
  "six-flags/six-flags-new-england": "six-flags-new-england",
  "six-flags/six-flags-over-georgia": "six-flags-over-georgia",
  "six-flags/six-flags-over-texas": "six-flags-over-texas",
  "six-flags/six-flags-qiddiya-city": "six-flags-qiddiya-city",
  "six-flags/six-flags-stlouis": "six-flags-st-louis",
  "samsung-cnt/caribbean-bay": "caribbean-bay",
  "samsung-cnt/everland": "everland",
};
